apiVersion: v1
kind: Secret
metadata:
  name: locust-storage
type: Opaque
data:
  azurestorageaccountname: {{ .Values.azureFile.storage.name | b64enc }}
  azurestorageaccountkey: {{ .Values.azureFile.storage.key | b64enc }}